### ISSUE TITLE
Inconsistent Casing For TransientMap in ChaincodeProposalPayload

### ISSUE THREAD

**Issue by jonmchan** [hyperledger/fabric-protos#71]
It would appear the convention is to utilize snake casing for message field names and CamelCasing for the message name or the type.  In peer/proposal.proto, that convention is broken with TransientMap.

https://github.com/hyperledger/fabric-protos/blob/318e632e5e0c668a1be9e1f882f814f179460766/peer/proposal.proto#L228

I realize this may be impossible to fix at this point with how many SDKs and clients that have hardcoded this field name, but here's to hoping it can get fixed in a v2. :)

**Comment by jt-nti** [comment]
Hi @jonmchan, thanks for the issue. Unfortunately the existing protos have quite a few problems regarding naming conventions, for example in the following files just for the snake casing for message field name convention you mention:

- common/ledger.proto
- gossip/message.proto
- peer/chaincode_shim.proto
- peer/lifecycle/db.proto
- peer/proposal.proto
- peer/transaction.proto

Hopefully more recent additions are a bit better, e.g. gateway/gateway.proto, and ideally future changes will follow better practices, however I don't think it's worth the disruption going back and fixing naming issues in existing definitions.

I would like to update the fabric-protos build process at some point as part of work on #72, which would hopefully flag up future naming problems when building pull requests to enforce better practices.

**Comment by denyeart** [comment]
Agree with @jt-nti , I'll go ahead and close the issue.
